USE PRUEBA_TECNICA
-- CLIENTE DATA
INSERT INTO CLIENTE (PRIMER_NOMBRE, PRIMER_APELLIDO, TIPO_DOC, NUMERO_DOCUMENTO, CELULAR, DIRECCION, CORREO ) 
	VALUES('Pepito', 'Perez', 'cc', '60345123', '312125232', 'Cll 1 #2-3', 'pepe@yopmail.com')

INSERT INTO CLIENTE (PRIMER_NOMBRE, PRIMER_APELLIDO, TIPO_DOC, NUMERO_DOCUMENTO, CELULAR, DIRECCION, CORREO ) 
	VALUES('María', 'Mendez', 'cc', '4032473', '312023232', 'Cll 3 #4-5', 'maria@yopmail.com')

INSERT INTO CLIENTE (PRIMER_NOMBRE, PRIMER_APELLIDO, TIPO_DOC, NUMERO_DOCUMENTO, CELULAR, DIRECCION, CORREO ) 
	VALUES('Alex', 'Salcedo', 'cc', '120456123', '3204563215', 'Cll 6 #7-8', 'alez@yopmail.com')

-- MECANICO DATA
INSERT INTO MECANICO (PRIMER_NOMBRE, PRIMER_APELLIDO, TIPO_DOC, NUMERO_DOCUMENTO, CELULAR, DIRECCION, CORREO, ESTADO)
	VALUES('Juan', 'Olguin', 'cc', '1052632145', '3002563214', 'CLL 7 #8-9', 'juan@carcenter.com', 'activo')

INSERT INTO MECANICO (PRIMER_NOMBRE, PRIMER_APELLIDO, TIPO_DOC, NUMERO_DOCUMENTO, CELULAR, DIRECCION, CORREO, ESTADO)
	VALUES('Luis', 'Novoa', 'cc', '1059369852', '3012514714', 'CLL 8 #9-10', 'luis@carcenter.com', 'activo')

-- REPUESTO DATA
INSERT INTO REPUESTO (NOMBRE, PRECIO_UNIDAD, STOCK) VALUES ('Rin', 500000, 20)
INSERT INTO REPUESTO (NOMBRE, PRECIO_UNIDAD, STOCK) VALUES ('Discos Frenos', 200000, 20)
INSERT INTO REPUESTO (NOMBRE, PRECIO_UNIDAD, STOCK) VALUES ('Amortiguadores', 100000, 20)
INSERT INTO REPUESTO (NOMBRE, PRECIO_UNIDAD, STOCK) VALUES ('Batería', 50000, 20)
INSERT INTO REPUESTO (NOMBRE, PRECIO_UNIDAD, STOCK) VALUES ('Pastillas de Frenos', 20000, 20)

-- SERVICIOS DATA
INSERT INTO SERVICIO (NOMBRE, VALOR_MINIMO, VALOR_MAXIMO) VALUES ('Cambio aceite', 80000, 140000)
INSERT INTO SERVICIO (NOMBRE, VALOR_MINIMO, VALOR_MAXIMO) VALUES ('Alineación Ejes', 320000, 450000)

-- TALLER DATA
INSERT INTO TALLER (DIRECCION, CIUDAD) VALUES ('CLL 20 #21-22', 'Bogota')

-- SERVICIOS DATA
--INSERT INTO SERVICIO (NOMBRE, VALOR_MAXIMO, VALOR_MINIMO) VALUES ('Cambio aceite', 140000, 80000)

-- FACTURA DATA
INSERT INTO FACTURA (ESTADO, CLIENTE_ID, MECANICO_ID, TALLER_ID, FECHA_CREACION)
	VALUES('terminado', 2, 1, 1, GETDATE())

INSERT INTO FACTURA_REPUESTOS (REPUESTO_ID, FACTURA_ID, CANTIDAD) VALUES (3, 1, 1);


-- FACTURA 2 DATA
INSERT INTO FACTURA (ESTADO, CLIENTE_ID, MECANICO_ID, TALLER_ID, FECHA_CREACION)
	VALUES('terminado', 1, 2, 1, DATEADD(DAY, -35, GETDATE()))

INSERT INTO FACTURA_REPUESTOS (REPUESTO_ID, FACTURA_ID, CANTIDAD) VALUES (3, 2, 3);
INSERT INTO FACTURA_REPUESTOS (REPUESTO_ID, FACTURA_ID, CANTIDAD) VALUES (1, 2, 2);
INSERT INTO FACTURA_REPUESTOS (REPUESTO_ID, FACTURA_ID, CANTIDAD) VALUES (2, 2, 4);

INSERT INTO FACTURA_SERVICIO (FACTURA_ID, SERVICIO_ID, PRECIO, DESCUENTO) VALUES (2, 1, 140000, 0)
INSERT INTO FACTURA_SERVICIO (FACTURA_ID, SERVICIO_ID, PRECIO, DESCUENTO) VALUES (2, 2, 320000, 0)

-- FACTURA 3 DATA
INSERT INTO FACTURA (ESTADO, CLIENTE_ID, MECANICO_ID, TALLER_ID, FECHA_CREACION)
	VALUES('terminado', 2, 1, 1, DATEADD(DAY, -2, GETDATE()))
