CREATE DATABASE PRUEBA_TECNICA
USE PRUEBA_TECNICA

CREATE TABLE CLIENTE (
	ID INT NOT NULL IDENTITY(1,1),
	PRIMER_NOMBRE VARCHAR(30) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(30) NULL,
	PRIMER_APELLIDO VARCHAR(30) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(30) NULL,
	TIPO_DOC VARCHAR(10) NOT NULL,
	NUMERO_DOCUMENTO VARCHAR(15) NOT NULL,
	CELULAR VARCHAR(15) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL
)

CREATE TABLE MECANICO (
	ID INT NOT NULL IDENTITY(1,1),
	PRIMER_NOMBRE VARCHAR(30) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(30) NULL,
	PRIMER_APELLIDO VARCHAR(30) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(30) NULL,
	TIPO_DOC VARCHAR(10) NOT NULL,
	NUMERO_DOCUMENTO VARCHAR(15) NOT NULL,
	CELULAR VARCHAR(15) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(15) NOT NULL
)

CREATE TABLE REPUESTO (
	ID INT NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	PRECIO_UNIDAD MONEY NOT NULL,
	STOCK INT NOT NULL
)

CREATE TABLE TALLER (
	ID INT NOT NULL IDENTITY(1,1),
	DIRECCION VARCHAR(50) NOT NULL,
	CIUDAD VARCHAR(50) NOT NULL
)

CREATE TABLE SERVICIO (
	ID INT NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	VALOR_MINIMO MONEY NOT NULL,
	VALOR_MAXIMO MONEY NOT NULL
)

CREATE TABLE FACTURA (
	ID INT NOT NULL IDENTITY(1,1),
	ESTADO VARCHAR(15) NOT NULL,
	CLIENTE_ID INT NOT NULL,
	MECANICO_ID INT NOT NULL,
	PRESUPUESTO MONEY NULL,
	TALLER_ID INT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	TOTAL MONEY NULL
)

CREATE TABLE FACTURA_REPUESTOS (
	REPUESTO_ID INT NOT NULL,
	FACTURA_ID INT NOT NULL,
	CANTIDAD INT NOT NULL
)

CREATE TABLE FACTURA_SERVICIO (
	FACTURA_ID INT NOT NULL,
	SERVICIO_ID INT NOT NULL,
	PRECIO MONEY NOT NULL,
	DESCUENTO MONEY NOT NULL
)