ALTER TABLE CLIENTE ADD PRIMARY KEY (ID)
ALTER TABLE MECANICO ADD PRIMARY KEY (ID)
ALTER TABLE REPUESTO ADD PRIMARY KEY (ID)
ALTER TABLE TALLER ADD PRIMARY KEY (ID)
ALTER TABLE SERVICIO ADD PRIMARY KEY (ID)

ALTER TABLE FACTURA ADD PRIMARY KEY (ID)
ALTER TABLE FACTURA ADD FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
ALTER TABLE FACTURA ADD FOREIGN KEY (MECANICO_ID) REFERENCES MECANICO(ID)
ALTER TABLE FACTURA ADD FOREIGN KEY (TALLER_ID) REFERENCES TALLER(ID)

ALTER TABLE FACTURA_REPUESTOS ADD PRIMARY KEY (FACTURA_ID,REPUESTO_ID)
ALTER TABLE FACTURA_REPUESTOS ADD FOREIGN KEY (FACTURA_ID) REFERENCES FACTURA(ID)
ALTER TABLE FACTURA_REPUESTOS ADD FOREIGN KEY (REPUESTO_ID) REFERENCES REPUESTO(ID)

ALTER TABLE FACTURA_SERVICIO ADD PRIMARY KEY (FACTURA_ID,SERVICIO_ID)
ALTER TABLE FACTURA_SERVICIO ADD FOREIGN KEY (FACTURA_ID) REFERENCES FACTURA(ID)
ALTER TABLE FACTURA_SERVICIO ADD FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(ID)