-- Consulta de Clientes que han comprado un acumulado DE MÁS DE $100.000 en los últimos 60 días
SELECT 
	CONCAT_WS(' ', C.PRIMER_NOMBRE, C.SEGUNDO_NOMBRE, C.PRIMER_APELLIDO, C.SEGUNDO_APELLIDO) AS CLIENTE,
	F.TOTAL
FROM CLIENTE C
	INNER JOIN FACTURA F ON C.ID = F.CLIENTE_ID
WHERE F.FECHA_CREACION >= DATEADD(DAY, -60, GETDATE()) AND F.ESTADO = 'terminado' AND F.TOTAL > 100000