-- Consulta de los 100 productos más vendidos en los últimos 30 días
SELECT
	R.NOMBRE AS PRODUCTO, SUM(FR.CANTIDAD) AS CANTIDAD 
FROM FACTURA_REPUESTOS FR
	INNER JOIN REPUESTO R ON FR.REPUESTO_ID = R.ID
	INNER JOIN FACTURA F ON FR.FACTURA_ID = F.ID
WHERE F.FECHA_CREACION >= DATEADD(DAY, -30, GETDATE())
GROUP BY R.NOMBRE