CREATE PROCEDURE RESTAR_STOCK_PRODUCTO (@FACTURA_ID INT, @PRODUCTO_ID INT, @CANTIDAD INT)
AS
BEGIN

	--1) Agrega repuesto a la factura
	INSERT INTO FACTURA_REPUESTOS(FACTURA_ID, REPUESTO_ID, CANTIDAD)
		VALUES (@FACTURA_ID, @PRODUCTO_ID, @CANTIDAD)

	--2) Una vez asociado el repuesto a la factura, se hace el respectivo ajuste al stock
	UPDATE REPUESTO SET STOCK = STOCK - @CANTIDAD WHERE ID = @PRODUCTO_ID
	
END
EXEC RESTAR_STOCK_PRODUCTO @FACTURA_ID = 3, @PRODUCTO_ID = 2, @CANTIDAD = 5